### ISSUE TITLE
llavaconfig error 

### ISSUE THREAD

**Issue by homiec** [LLaVA-VL/LLaVA-NeXT#62]
File "/home/ma-user/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlavaConfig' object has no attribute 'mlp_bias'   

What is the cause of this problem?

**Comment by Stevetich** [comment]
I also have this problem when trying to test the inference with _LLaVA-NeXT-Video-7B-DPO_.

**Comment by Stevetich** [comment]
> I also have this problem when trying to test the inference with _LLaVA-NeXT-Video-7B-DPO_.

It seems I have fixed this problem. We have to build the environment by `pip install -e ".[train]"`.

**Comment by linzy5** [comment]
@reachsak Hi, in the pyproject.toml, the train target require transformers version is : 
```
"transformers@git+https://github.com/huggingface/transformers.git@1c39974a4c4036fd641bc1191cc32799f85715a4"
```
I uninstall transformers and reinstall by 
```
pip install transformers@git+https://github.com/huggingface/transformers.git@1c39974a4c4036fd641bc1191cc32799f85715a4
```
solved the problem.

The werid thing is, I check the transformers version, the versions after 4.40.0 is conclude this commit, "1c39974a4c4036fd641bc1191cc32799f85715a4", I dont know this issue still happened.
